export enum Array2DAction {
  SET_CELLS = 'SetCells',
  INSERT_CELLS = 'InsertCells',
  REMOVE_CELLS = 'RemoveCells',
  PUSH_CELLS = 'PushCells',
  POP_CELLS = 'PopCells',
  SHIFT_CELLS = 'ShiftCells',
  UNSHIFT_CELLS = 'UnshiftCells',
  INSERT_ROWS = 'InsertRows',
  PUSH_ROWS = 'PushRows',
  POP_ROWS = 'PopRows',
  SHIFT_ROWS = 'ShiftRows',
  UNSHIFT_ROWS = 'UnshiftRows',
  SET_CELLS_HIGHLIGHT = 'SetCellsHighlight',
  CLEAR_CELLS_HIGHLIGHT = 'ClearCellsHighlight',
  CLEAR_ALL_CELLS_HIGHLIGHT = 'ClearAllCellsHighlight',
  CLEAR_ALL_ROWS_HIGHLIGHT = 'ClearAllRowsHighlight',
}